language: rust
env:
  global:
    - secure: d9XdPvxkk3oABKds9K3SHCfVH/mW3Bls6aUScRRYhsYdQOoNYflDsApqjSFxJEHXuHN2RONkiVds1u1g1YQtkFU3iNPo9qA26tFqV400dRraBPbpm2c/TiH6VeAqto1Rv3+R35BGh1Cw9MO/YBbRW0EPvQ/8bk7fpCLUw/YlSqs=

script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose

after_script:
  - ln -s target/doc doc
  - curl -v http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN > ./upload-docs
  - python -c 'print(open("upload-docs").read())'
  - sh ./upload-docs
